services:
  - type: web
    name: smartmarketai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/dashboard.py --server.port=10000 --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
